import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "پربازدیدترین رسانه گردشگری ایران",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      className="h-full antialiased rtl-enabled"
      suppressHydrationWarning
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
