import UserModel from "./User";
import OTPModel from "./OTP";
import CategoryModle from "./Category";
import ArticleModle from "./Article";
import ListModel from "./List";
import BannerModel from "./Banner";
import AdvertisementModel from "./Advertisement";
import CommentModel from "./Comment";
import ArticleCategoryModel from "./ArticleCategory";
import FollowModel from "./Follow";
import BookmarkModel from "./Bookmark";

export const User = UserModel;
export const OTP = OTPModel;
export const Category = CategoryModle;
export const Article = ArticleModle;
export const List = ListModel;
export const Banner = BannerModel;
export const Advertisement = AdvertisementModel;
export const Comment = CommentModel;
export const ArticleCategory = ArticleCategoryModel;
export const Follow = FollowModel;
export const Bookmark = BookmarkModel;